# 开发环境配置

server:
  port: 8765

spring:
  banner:
    charset: UTF-8
    location: classpath:isc-volunteer-banner.txt
  datasource:
    username: root
    password: zyy7112003.
    url: jdbc:mysql:///isc-volunteer
  data:
    redis:
      port: 6379
      password: zyy7112003.
      database: 0
      host: 127.0.0.1

