# 开发环境配置

server:
  port: 8765

spring:
  banner:
    charset: UTF-8
    location: classpath:isc-volunteer-banner.txt
  datasource:
    username: root
    password: zyy7112003.
    url: jdbc:mysql:///isc-volunteer
  data:
    redis:
      port: 6379
      password: zyy7112003.
      database: 0
      host: 127.0.0.1

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.isc.backstage
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
