server:
  port: 8888

spring:
  datasource:
    username: root
    password: zyy20031222
    url: jdbc:mysql:///iscweb
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
