server:
  port: 8081

spring:
  datasource:
    username: root
    password: zyy20031222
    url: jdbc:mysql:///xdb

  redis:
    port: 6379
    host: localhost


logging:
  level:
    com.isc: debug


